### ISSUE TITLE
[login] If fetching fstab fails, a TypeError follows

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-contentsource-connector#304]
With the code in `getProjectConfig`:

https://github.com/adobe/helix-contentsource-connector/blob/b4862a2d5db94e15f00405bcbb189fb2faa5ea3e/src/index.js#L197-L198

the result contains an undefined `mp` which then causes a:
```
error while invoking function TypeError: Cannot read properties of undefined (reading 'type')
at run (/var/task/index.js:682596:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async lambdaAdapter (/var/task/index.js:14403:22)
at async Runtime.wrapped [as handler] (/var/task/index.js:14464:14)
```
in the `login` route:

https://github.com/adobe/helix-contentsource-connector/blob/b4862a2d5db94e15f00405bcbb189fb2faa5ea3e/src/index.js#L362-L364

**Comment by dominique-pfister** [comment]
fixed with https://github.com/adobe/helix-contentsource-connector/commit/7e6ac2c6ba1ebd827dc87848ae4c6064b5e7cfb0
